### ISSUE TITLE
Szlovákia helyett Csehország

### ISSUE THREAD

**Issue by draconesse** [tamas-ferenci/GondolatokAJarvanyugyiAdatokKozleserol#1]
Kedves Tamás!
A **Néhány kiegészítő megjegyzés** fejezetben találtam egy pontatlanságot:
Szlovákia: https://onemocneni-aktualne.mzcr.cz/covid-19
A link a cseh egészségügyi minisztérium honlapjára mutat, nem a szlovákéra.
Szlovák oldalakból a következőket (angol nyelvű változat is elérhető!) ajánlom:
[https://korona.gov.sk/en/coronavirus-covid-19-in-the-slovak-republic-in-numbers/](https://korona.gov.sk/en/coronavirus-covid-19-in-the-slovak-republic-in-numbers/)
[https://covid-19.nczisk.sk/en/](https://covid-19.nczisk.sk/en/)
Köszönöm az írást!
katadoromb

**Comment by ferenci-tamas** [comment]
Kedves Kata!

Köszönöm! Ezt jól elnéztem. Javítottam, és akkor már beleraktam tényleg Szlovákiát is. Még egyszer köszönöm!

Tamás
